### ISSUE TITLE
IDs used by datalad-ukb

### ISSUE THREAD

**Issue by djarecka** [datalad/datalad-ukbiobank#16]
I have to datalize one dataset that contains data from the UK Biobank, and decided to try to use `datalad-ukbiobank`. I'm receiving various sets of errors, but I believe I should start from making sure that I understand IDs datalad expects. 

When I'm checking my biobank project descriptions, I have something that is called `Application ID` and `Bucket ID`,  but `ukb-init` expects `PARTICPANT-ID` and `DATARECORD-ID`. I've used `Application ID` for  `PARTICPANT-ID` and `Bucket ID` for `DATARECORD-ID`, but not sure if this was right, the IDs that can be found in the help has a different format.

**Comment by loj** [comment]
@djarecka `ukb-init` and `ukb-update` are used to download bulk data from the UK-biobank.

You'll need to use the UK-biobank's `ukbconv` tool to generate a "bulk file" which lists participant-eids and field numbers for your application.

You can then use the participant eids as the `PARTICPANT-ID` and the field numbers as the`DATARECORD-ID` with `ukb-init`

**Comment by AlexandreHutton** [comment]
To extend the previous reply, here are the steps required before ukb-update:
1) Download .enc file from UKBB (Showcase -> Data -> Bucket ID -> Input MD5 -> Download)
2) ukbunpack ukb123.enc -aKEYFILE (Create ukb123.enc_ukb)
3) ukbconv ukb123.enc_ukb bulk -eENCODING (the encoding file can be found with the utilities).
4) Resultant file is ukb123.bulk, with the subject-datafield pairs: "PARTICIPANT DATAFIELD" (one pair per line, space-delimited).

Parse and use "datalad ukb-init [PARTICIPANT] [DATAFIELD]."
Note: I recommend that you do _not_ put these in a superdataset yet since parallel downloads will cause the different threads to throw errors when they try to lock the same file in the superdataset. The same applies to threads working on the same participant.

**Comment by djarecka** [comment]
@loj @AlexandreHutton - thanks for your response!

I was able to initialize and update/download files following your instruction, but perhaps I'm missing a bigger picture, since it's not clear to me why the `ukb-init` command works on a single participant id... Does it mean that the idea would be to put each participant in a different dataset? 
Would this mean, that `ukb-update` helps me only with updates for the specific subject, and does not help me when UKBB adds more subjects?

cc: @hoda1394

**Comment by AlexandreHutton** [comment]
> Does it mean that the idea would be to put each participant in a different dataset?
Yes. The alternative of having all subjects in a single dataset causes Datalad to crash due to the large number of files created (e.g., for only the T1s in the current 40k release, you end up with ~31M files). It would also be impossible to have multiple download threads, making it ~10x slower.

> Would this mean, that ukb-update helps me only with updates for the specific subject, and does not help me when UKBB adds more subjects?  
Correct. New subjects would need to be added by running ukb-init again.

**Comment by djarecka** [comment]
Thanks @AlexandreHutton for the clarification!

Also, I had one more issue related to the length of the file. So, the parent directory of my project is a symlink to the directory that has longer name, and when `datald-ukb` creates a path of the output file for the `ukbfetch` command, it uses the longer target path  `ukbfetch` starts complaining `Invalid output file File names must be 1-64 characters long`.  Do you have any recommendation? (besides using one-letter-long name of the datasets ;-) 
Let me know if you want me to ask it in a separate issue!

**Comment by AlexandreHutton** [comment]
It's a different issue. The easiest thing is to put it in a higher-level directory (e.g. /home/djarecka/data/) and then move the files where you want them once they're done downloading (__provided that both directories are on the same filesystem__, moving the top-level directory won't take any time).

**Comment by djarecka** [comment]
ok, thanks. 

I was wondering  if `datalad` can have an option to keep the symlink instead of target for the output file, but perhaps it can lead to different issues.
